# Generated by Django 4.2 on 2023-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_asistencia_deportista_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='asistencia',
            new_name='asistio',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='deporte',
        ),
        migrations.AddField(
            model_name='profesor',
            name='deporte',
            field=models.ManyToManyField(to='libreria.entrenamiento'),
        ),
    ]
