# Generated by Django 4.2 on 2023-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_asistencia_asistencia_asistio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='deporte',
        ),
        migrations.AddField(
            model_name='profesor',
            name='deporte',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
